name: Check CLA

on:
  pull_request:
    types: [opened]

jobs:
  check-cla:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Check CLA
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python checkcla.py
